name: datacard
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  pin_code_fields: ^7.4.0
  flutter_svg: ^2.0.2
  image_picker: ^0.8.6+4
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  file_picker: ^5.2.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.0.1
  intl: ^0.17.0
  flutter_pdfview: ^1.2.9
  http: ^0.13.5
  path_provider: ^2.0.13
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  firebase_messaging: ^14.3.0
  flutter_local_notifications: ^13.0.0
  fluttertoast: ^8.2.1
  cached_network_image: ^3.2.3
  webview_flutter: ^4.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
